steps:

- id: "Gerando service-account-storage.json"
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - kms
    - decrypt
    - --key=service-accoount-storage
    - --keyring=codeflix
    - --location=global
    - --plaintext-file=./storage/credentials/google/service-account-storage.json
    - --ciphertext-file=./storage/credentials/google/service-account-storage.json.enc

- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
  env:
    - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
    - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
    - GOOGLE_CLOUD_STORAGE_BUCKET=code-micro-videos-leticia
    - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/code-micro-videos-leticia
    - TESTING_PROD=true

- id: "Permissão em /var/www"
  name: 'docker'
  args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

- id: "Rodando docker ps"
  name: 'docker'
  args: ['ps']

- id: "Rodando composer install"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

- id: "Limpando Cache"
  name: 'docker'
  args: ['exec','-t','micro-videos-app','php','/var/www/artisan','cache:clear']

- id: "Limpando Cache Configuração"
  name: 'docker'
  args: ['exec','-t','micro-videos-app','php','/var/www/artisan','config:clear']

- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

- id: "Cat .env"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cat', '.env']

- id: "Copiando .env.testing"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.testing.example', '.env.testing']

- id: "Cat .env.testing"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'cat', '.env.testing']

- id: "Rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando migrations"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

- id: "Rodando teste unitário do PHPUnit"
  name: 'docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
